sudo: required
language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules

node_js:
  - '12'

os:
  - linux


stages:
  - install
  - test
  - build
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: install
      script: 
        - npm install
        - npm install codecov
    - stage: test
      script: 
        - npm run lint
        - npm test
        - npm run coverage
    - stage: build
      script:
      - npm run build
    - stage: deploy
      script:
      - npm install @semantic-release/changelog @semantic-release/git
      - npx semantic-release
