sudo: required
language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules

node_js:
  - '12'

os:
  - linux

before_install:
- npm install -g @semantic-release/changelog @semantic-release/git @semantic-release/exec

jobs:
  include:
    - stage: release
      script:
        - npm run lint
        - npm test
        - npm run build
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - npx semantic-release