sudo: required
language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
node_js:
  - '14'
  - '12'
  - '10'
stages:
  - install
  - test
  - build
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: install
      script: 
        - npm install -g codecov
        - npm install
      skip_cleanup: true
    - stage: test
      script: 
        - npm run lint
        - npm test
        - codecov
      skip_cleanup: true
    - stage: build
      script:
      - npm run build
      skip_cleanup: true
    - stage: deploy
      script:
      - npm install -g @semantic-release/changelog @semantic-release/git
      - npx semantic-release
