language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
node_js:
  - '14'
  - '12'
  - '10'
install:
  - npm install -g codecov
  - npm install
script:
  - npm run lint
  - npm test
  - codecov
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      npx travis-deploy-once --pro && npm run build && npm install -g @semantic-release/changelog @semantic-release/git  semantic-release && semantic-release;
    fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/