language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
node_js:
  - '14'
  - '12'
  - '10'

jobs:
  include:
    - stage: install
      script: 
        - npm install -g codecov
        - npm install
      skip_cleanup: true
    - stage: test
      script: 
        - npm run lint
        - npm test
        - codecov
      skip_cleanup: true
    - stage: Build & publish
      script:
      - npm run build
      - npm install -g @semantic-release/changelog @semantic-release/git
      - npx semantic-release
      if: branch = master
